INSERT INTO `Administrador` (`idAdministrador`, `usuario`, `contrasenna`) VALUES (NULL, 'admin1', 'admin1'), (NULL, 'admin2', 'admin2');

INSERT INTO `Categoria` (`idCategoria`, `nombre`, `emailDepartamento`) VALUES (NULL, 'Entrantes', 'entrante@ikasle.com'), (NULL, 'Pescados', 'pescados@ikasle.com'), (NULL, 'Postres', 'postres@ikasle.com'), (NULL, 'Ensaladas', 'postres@ikasle.com');

INSERT INTO `TipoVenta` (`idTipoVenta`, `tipoVenta`) VALUES (NULL, 'kilos'), (NULL, 'raciones');

INSERT INTO `Plato` (`idPlato`, `nombre`, `precio`, `unidadesMinimas`, `notas`, `imagen`, `idCategoria`, `idTipoVenta`, `estado`) VALUES (NULL, 'Setas a la plancha', '5', '1', 'Alérgenos Hongos', 'http://4.bp.blogspot.com/_iQCEs3lfzVQ/SOEa1YmXjoI/AAAAAAAAAF8/CvcPgjfz1a4/w1200-h630-p-k-no-nu/setasplancha+(2).JPG', '4', '2','1'), (NULL, 'Entrecot con patatas', '15', '1', 'No apto para vegetarianos', 'https://www.hogarmania.com/archivos/201105/0692-entrecote-de-bistrot-xl-668x400x80xX.jpg', '1', '2','1'), (NULL, 'Merluza al vapor', '10', '2', 'Alto omega3', 'https://www.hogarmania.com/archivos/201404/1443-merluza-al-vapor-con-vinagreta-de-tomate-y-aceite-de-trufa-blanca-627-xl-668x400x80xX.jpg', '2', '1','1'), (NULL, 'Tarta de queso', '3', '4', 'Alto contenido de lactosa', 'https://unareceta.com/wp-content/uploads/2017/02/tarta-de-queso-sin-horno-facil-640x428.jpg', '3', '2','1'), (NULL, 'Salmón con especias', '15', '2', 'No apto para alérgicos a los pescados', 'https://www.canalcocina.es/medias/images/1605CocinaDeFamiliaT4SalmonMarinadoSalsaMostaza2.jpg', '2', '1', '1'), (NULL, 'Paella tradicional', '5', '5', 'Contiene crustacios', 'http://recetaspaella.es/img/paella-mixta-665.jpg', '1', '1', '1');

INSERT INTO `Pedido` (`idPedido`, `nombre`, `apellidos`, `email`, `telefono`, `fechaEntrega`, `total`) VALUES (NULL, 'Jon', 'Xu', 'mygoldxp@msn.com', '666666666', '2019-01-31', 150.0), (NULL, 'Sebas', 'Zawisza', 'sebas@sebas.com', '999999999', '2019-02-07', 200.5), (NULL, 'Imanol Luis', 'Hidalgo', 'imanol@imanol.com', '88888888', '2019-02-07', 105.00);

INSERT INTO `DetallePedido` (`idPedido`, `idPlato`, `cantidad`) VALUES ('1', '6', '2'), ('1', '1', '4'), ('1', '2', '6'), ('3', '3', '3'), ('3', '4', '7'), ('3', '5', '5'), ('2', '6', '2'), ('2', '1', '5'), ('2', '2', '5'), ('2', '3', '7'), ('2', '4', '5'), ('2', '5', '6');